name: emailed
description: emailed
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  injectable: ^2.1.0
  get_it: ^7.2.0

  cache:
    path: ./cache/
  data:
    path: ./data/
  domain:
    path: ./domain/


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  injectable_generator: ^2.1.3
  build_runner: ^2.3.3

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true


  assets:
     - assets/images/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

